---
# Wrapper to start squidmulti

- name: begin squidmulti management
  hosts: all
  vars_files:
    - roles/squidmulti/vars/{{ proxy_location }}.yml

  roles:
  - role: squidmulti
    state: "{{ squidmulti_state }}"
