---
# Install / Uninstall squid client settings

- name: Install proxy settings
  include: install.yml
  when: state == present

- name: Uninstall proxy settings
  include: uninstall.yml
  when: state == absent
