---
# Install / Uninstall squid client settings

- name: Install client proxy settings
  include_tasks: squid_client_uninstall.yml
  when: state == 'absent'

- name: Uninstall client proxy settings
  include_tasks: squid_client_uninstall.yml
  when: state == 'absent'
