---
- name: Remove /etc/profile/http_proxy.csh
  file:
    path: /etc/profile.d/http_proxy.csh
    state: absent

- name: Remove /etc/profile/http_proxy.sh
  file:
    path: /etc/profile.d/http_proxy.sh
    state: absent

- name: Remove env variable for http_proxy
  lineinfile:
    path: /etc/environment
    regexp: '^http_proxy='
    state: absent

- name: Remove env variable for http_proxy
  lineinfile:
    path: /etc/environment
    regexp: '^https_proxy='
    state: absent
    
#- name: Add a line to a file if the file does not exist, without passing regexp
#  lineinfile:
#    path: /etc/environment
#    regexp: '^REQUESTS_CA_BUNDLE='
#    state: absent
