---
# Handlers

# Restart squid service
- name: restart squid
  service:
    name: squid
    state: restarted

- name: reload squid
  service:
    name: squid
    state: reloaded

# Restart firewalld service
- name: restart iptables
  service:
    name: iptables
    state: restarted
