---
# This playbook deploys the whole application stack in this site.

- name: Playbook to print the pubkey value
  hosts: all


- name: Ansible create file with content example
  template:
    src: squidCA.pem.j2
    dest: /etc/squid/ssl_cert/squidCA.test
- name: Create a DOS-style text file from a template
  template:
    src: config.ini.j2
    dest: /share/windows/config.ini
    newline_sequence: '\r\n
