---
# Copy certificate to dir

- name: Playbook to print the pubkey value
  hosts: all

tasks:
 - name: Do a template
   template:
     src: squidCA.pem.j2
     dest: /etc/squid/ssl_cert/squidCA.test
