---
# This playbook deploys the whole application stack in this site.

- name: Playbook to print the pubkey value
  hosts: all

  tasks:
  - name: Ansible create file with content example
    copy:
      dest: "/etc/test.txt"
      content: "{{ infosec_ssl_squid.PUBLIC_KEY }}"
