---
- name: Copy template
  hosts: all
  vars:
    shares:
      - name: raida-rw-isl-nsc
        serverOptions: "rw,insecure_locks,no_subtree_check"
        clientOptions: "x-systemd.automount,rw"
        clientList:
          {{ clients["raida-rw-isl-nsc-clients"].clients }}
      - name: raida-ro-nsc
        serverOptions: "ro,no_subtree_check"
        clientOptions: "ro"
        clientList:
          {{ clients["raida-ro-nsc-clients"].clients }}
    clients:
      - name: raida-rw-isl-nsc-clients
        clients:
          - 192.168.56.51
          - 192.168.56.62

      - name: raida-ro-nsc-clients
        clients:
          - 192.168.56.55
          - 192.168.56.66
  tasks:
  - name: write /etc/exports file from source control
    template:
      src: ../templates/test.j2
      dest: /var/tmp/test.out
