---
- include_vars:
    file: ../vars/proxy_hosts.yml

- name: copy config - static global files
  copy:
    src: etc/squidglobal/
    dest: /etc/{{ item.name }}/
    owner: squid
    group: squid
    mode: u=rw,g=r,o=r
    seuser: system_u
    setype: squid_conf_t
  loop: "{{ squid_instances }}"

- name: copy config - template port file
  template:
    src: etc/squidglobal/g_ports.conf.j2
    dest: /etc/{{ item.name }}/g_ports.conf
    owner: squid
    group: squid
    mode: u=rw,g=r,o=r
    seuser: system_u
    setype: squid_conf_t
  loop: "{{ squid_instances }}"

- name: copy config - template restrictive acl
  template:
    src: etc/squidglobal/g_acl_restrictive.conf.j2
    dest: /etc/{{ item.name }}/g_acl_restrictive.conf
    owner: squid
    group: squid
    mode: u=rw,g=r,o=r
    seuser: system_u
    setype: squid_conf_t
  loop: "{{ squid_instances }}"

- name: copy config - restrictive sites
  copy:
    src: etc/{{ item.name }}/sites
    dest: /etc/{{ item.name }}/sites
    owner: squid
    group: squid
    mode: u=rw,g=r,o=r
    seuser: system_u
    setype: squid_conf_t
  loop: "{{ squid_instances }}"
  when: item.acl_type == "restrictive"

- name: copy config - create {{ item.name }}.conf
  copy:
    src: etc/squidglobal/squid.conf
    dest: /etc/{{ item.name }}/{{ item.name }}.conf
    owner: squid
    group: squid
    mode: u=rw,g=r,o=r
    seuser: system_u
    setype: squid_conf_t
  loop: "{{ squid_instances }}"
