---
- name: stop service
  service:
    name: "{{ item.name }}"
    state: stopped
  loop: "{{ squid_instances }}"

- name: disable service
  service:
    name: "{{ item.name }}"
    state: disabled
  loop: "{{ squid_instances }}"

- name: delete unit file
  ansible.builtin.file:
    path: /usr/lib/systemd/system/{{ item.name }}.service
    state: absent
  loop: "{{ squid_instances }}"
