- name: Add iptables routing
  blockinfile:
    path: /etc/sysconfig/iptables
    insertafter: "##start_squid_multi"
    block: |
      -A PREROUTING -s {{ item.src_net }} -p tcp -m tcp --dport 80 -m comment --comment "80 to squid {{ item.port_http_proxy }}" -j REDIRECT --to-ports {{ item.port_http_proxy }}
      -A PREROUTING -s {{ item.src_net }} -p tcp -m tcp --dport 443 -m comment --comment "443 to squid {{ item.port_https_proxy }}" -j REDIRECT --to-ports {{ item.port_https_proxy }}
    marker: "# {mark} ANSIBLE SQUIDMULTI - {{item.name}}"
  loop: "{{ squid_instances }}"
  notify: restart iptables
