---
# Install / Uninstall squid client settings

- name: Install auditd
  include_tasks: copy_configs.yml
  when: state == 'present'
- name: Install auditd
  include_tasks: selinux_ports.yml
  when: state == 'present'
- name: Install auditd
  include_tasks: iptables.yml
  when: state == 'present'
- name: Install auditd
  include_tasks: system_service.yml
  when: state == 'present'
