---
# Install / Uninstall squid client settings

- name: copy config flies
  include_tasks: copy_configs.yml
  when: state == 'present'
- name: configure selinux ports
  include_tasks: selinux_ports.yml
  when: state == 'present'
- name: configure iptables
  include_tasks: iptables.yml
  when: state == 'present'
- name: create systemctl service
  include_tasks: system_service.yml
  when: state == 'present'

- name: update acl
  include_tasks: update_acls.yml
  when: state == 'update_acls'
