---
- name: create systemd service - place service.unit file
  template:
    src: usr/lib/systemd/system/service_name.service.4.9.j2
    dest: /usr/lib/systemd/system/{{ item.name }}.service
  loop: "{{ squid_instances }}"

- name: create systemd service - service state started
  service:
    name: "{{ item.name }}"
    state: started
  loop: "{{ squid_instances }}"
